"""
Query expansion module with spell correction, synonym expansion, and LLM support.
"""

import logging
from spellchecker import SpellChecker
from config import (
    MATH_SYNONYMS, 
    ENABLE_SPELL_CORRECTION, 
    ENABLE_SYNONYM_EXPANSION,
    ENABLE_LLM_EXPANSION
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize spell checker (lazy loading)
_spell_checker = None


def get_spell_checker():
    """Get or initialize the spell checker."""
    global _spell_checker
    if _spell_checker is None:
        _spell_checker = SpellChecker()
        # Add math-specific words to dictionary
        math_words = set([
            'calculus', 'algebra', 'geometry', 'trigonometry', 'topology',
            'differential', 'integral', 'derivative', 'matrix', 'vector',
            'theorem', 'lemma', 'proof', 'axiom', 'corollary', 'polynomial',
            'eigenvalue', 'eigenvector', 'determinant', 'fourier', 'laplace',
            'euclidean', 'gaussian', 'riemann', 'hilbert', 'banach', 'cauchy'
        ])
        _spell_checker.word_frequency.load_words(math_words)
    return _spell_checker


def correct_spelling(word):
    """
    Correct spelling of a single word.
    
    Args:
        word: Input word (string)
        
    Returns:
        Corrected word (string)
    """
    if not ENABLE_SPELL_CORRECTION:
        return word
    
    try:
        spell = get_spell_checker()
        
        # If word is in dictionary, return as-is
        if word in spell:
            return word
        
        # Get correction
        correction = spell.correction(word)
        
        # Only return correction if it's different and confident
        if correction and correction != word:
            logger.debug(f"Spell correction: {word} -> {correction}")
            return correction
        
        return word
        
    except Exception as e:
        logger.warning(f"Spell check error for '{word}': {e}")
        return word


def expand_with_synonyms(words):
    """
    Expand query words with synonyms from the math dictionary.
    
    Args:
        words: List of query words
        
    Returns:
        Set of words including originals and synonyms
    """
    if not ENABLE_SYNONYM_EXPANSION:
        return set(words)
    
    expanded = set(words)
    
    for word in words:
        # Check for exact match
        if word in MATH_SYNONYMS:
            synonyms = MATH_SYNONYMS[word]
            expanded.update(synonyms)
            logger.debug(f"Synonyms for '{word}': {synonyms}")
        
        # Check for multi-word phrases
        for phrase, synonyms in MATH_SYNONYMS.items():
            if ' ' in phrase:  # Multi-word phrase
                # Simple check if phrase appears in query
                query_str = ' '.join(words)
                if phrase in query_str:
                    expanded.update(synonyms)
                    logger.debug(f"Phrase synonyms for '{phrase}': {synonyms}")
    
    return expanded


def llm_expand_query(query):
    """
    Expand query using a local LLM (e.g., via Ollama).
    
    This is a STUB implementation. To enable:
    1. Install Ollama: https://ollama.ai/
    2. Pull a model: ollama pull llama2
    3. Uncomment the implementation below
    4. Set ENABLE_LLM_EXPANSION = True in config.py
    
    Args:
        query: Original query string
        
    Returns:
        List of related terms generated by LLM
    """
    if not ENABLE_LLM_EXPANSION:
        return []
    
    # STUB: Return empty list when LLM is not configured
    logger.info("LLM expansion is disabled. Set ENABLE_LLM_EXPANSION=True to enable.")
    return []
    
    # ===== UNCOMMENT BELOW TO ENABLE LLM EXPANSION =====
    """
    try:
        import requests
        
        # Ollama API endpoint
        url = "http://localhost:11434/api/generate"
        
        prompt = f'''Given the search query "{query}" for a mathematics search engine, 
        suggest 3-5 related mathematical terms or concepts that would help find relevant results.
        Output only the terms, separated by commas, no explanations.
        
        Query: {query}
        Related terms:'''
        
        payload = {
            "model": "llama2",  # or another model you have pulled
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.3,
                "max_tokens": 50
            }
        }
        
        response = requests.post(url, json=payload, timeout=10)
        
        if response.status_code == 200:
            result = response.json()
            generated_text = result.get('response', '')
            
            # Parse comma-separated terms
            terms = [term.strip().lower() for term in generated_text.split(',')]
            terms = [term for term in terms if term and len(term) > 2]
            
            logger.info(f"LLM expanded '{query}' with: {terms}")
            return terms
        else:
            logger.warning(f"LLM API returned status {response.status_code}")
            return []
            
    except Exception as e:
        logger.error(f"LLM expansion error: {e}")
        return []
    """


def expand_query(query):
    """
    Complete query expansion pipeline:
    1. Spell correction
    2. Synonym expansion
    3. LLM expansion (if enabled)
    
    Args:
        query: Original query string
        
    Returns:
        Set of expanded query terms
    """
    # Split query into words
    words = query.lower().split()
    
    # Step 1: Spell correction
    if ENABLE_SPELL_CORRECTION:
        corrected_words = [correct_spelling(word) for word in words]
        logger.debug(f"After spell correction: {corrected_words}")
    else:
        corrected_words = words
    
    # Step 2: Synonym expansion
    expanded_words = expand_with_synonyms(corrected_words)
    logger.debug(f"After synonym expansion: {expanded_words}")
    
    # Step 3: LLM expansion
    if ENABLE_LLM_EXPANSION:
        llm_terms = llm_expand_query(query)
        expanded_words.update(llm_terms)
        logger.debug(f"After LLM expansion: {expanded_words}")
    
    logger.info(f"Query expansion: '{query}' -> {expanded_words}")
    return expanded_words


if __name__ == "__main__":
    # Test query expansion
    test_queries = [
        "calculus",
        "diff eq",
        "integral calcalus",  # Misspelled
        "matrix theory",
        "topology"
    ]
    
    for query in test_queries:
        print(f"\nOriginal: {query}")
        expanded = expand_query(query)
        print(f"Expanded: {expanded}")
